### ISSUE TITLE
Error on Updated Nightly

### ISSUE THREAD

**Issue by willemneal** [mozilla/libdweb#63]
I updated the Firefox Nightly and somehow the location of it moved.  Note below that the script expected no space, and it moved to a folder with a space.  Renaming the folder worked, but I just wanted to leave this here if anyone else experiences this issue.

```
cross-env MOZ_DISABLE_CONTENT_SANDBOX=1 web-ext run --firefox=nightly --browser-console --url about:debugging --source-dir demo/fs

Applying config file: ./package.json
Running web extension from /Users/willem/OSD/libdweb/demo/fs
Error: spawn /Applications/FirefoxNightly.app/Contents/MacOS/firefox-bin ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libdweb@0.0.0 demo:fs: `cross-env MOZ_DISABLE_CONTENT_SANDBOX=1 web-ext run --firefox=nightly --browser-console --url about:debugging --source-dir demo/fs`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libdweb@0.0.0 demo:fs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/willem/.npm/_logs/2018-08-09T16_54_54_671Z-debug.log
```

**Comment by Gozala** [comment]
@willemneal thanks for reporting, I"m not sure I understand what has exactly happend. As I understand nightly on your system end up in a different location from what [web-ext](http://github.com/mozilla/web-ext/) tool expects. I think it's always possible to specify full path to a firefox rather than just shortname like `nightly` used by our scripts.

I would invite you to report the issue into [web-ext](http://github.com/mozilla/web-ext/) repo instead, as it's ultimately where that tool is being developed.
