### ISSUE TITLE
error opening input stream on linux

### ISSUE THREAD

**Issue by substack** [mozilla/libdweb#85]
Previously, the dweb examples worked for me. I get a crash in my ordinary firefox profile (#84) when I run the demos now, or if I run the demos using `web-ext` I get this error: 

```
Error opening input stream (invalid filename?): file:///home/substack/projects/libdweb/src/UDPSocket/Socket.js
```

The error only occurs when you try to actually use one of the APIs. For example, in the UDPSocket example it only prints this message when you `create --port 8005` in the REPL.

I had someone else also on linux install the latest nightly and they got exactly this same error running the libdweb demos.

**Comment by Gozala** [comment]
@substack  Did you notice we use this env variables for demo runs:
https://github.com/mozilla/libdweb/blob/master/package.json#L33-L41

It is required for when running WebExtensions from file system, but not if you've built it and then installed. That's due to process sandboxing used in Firefox, that has limited FS access. When you build it it's not an issue because in that case add-on is located where in place where that process has access to.

**Comment by substack** [comment]
Thanks @gozala. Setting MOZ_DISABLE_CONTENT_SANDBOX=1 fixes my error. For some reason changing the sandbox level in about:config didn't have the same effect.
